 
 
 
 SELECT *FROM EmployeeData;

 -- MODE VALUE
 SELECT* ,DENSE_RANK() OVER (ORDER BY[COUNT ALL] DESC) [DR] FROM
  (SELECT DEPARTMENT ,COUNT(*) [COUNT ALL] FROM EmployeeData
  GROUP BY  Department) X;

SELECT STRING_AGG(DEPARTMENT,',') [MODE] FROM
(SELECT* ,DENSE_RANK() OVER (ORDER BY[COUNT ALL] DESC) [DR] FROM
(SELECT DEPARTMENT ,COUNT(*) [COUNT ALL] FROM EmployeeData
GROUP BY  Department) X)Y WHERE DR=1;




