use[data profiling]

select * from EmployeeData

-- MAX
SELECT MAX(SALARY) FROM EMPLOYEEDATA
-- MIN
SELECT MIN(SALARY) FROM EMPLOYEEDATA
-- AVG
SELECT AVG (SALARY) FROM EmployeeData
--STDDEV
SELECT STDEV (SALARY) FROM EmployeeData

-- COUNT SALARY =0
SELECT COUNT(*) FROM EmployeeData
WHERE SALARY=0

-- COUNT SALRY OS NULL
SELECT COUNT(*) FROM EmployeeData
WHERE SALARY IS NULL

SELECT COUNT(DISTINCT SALARY) FROM EmployeeData
